development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      uri: mongodb+srv://<%= Rails.application.credentials.dig(:atlas, :user_id) %>:<%= Rails.application.credentials.dig(:atlas, :password) %>@cluster90016.m6qysai.mongodb.net/speedway_mb25_development
      options:
        heartbeat_frequency: 10000
  # Configure Mongoid-specific options. (optional)
  options:
    log_level: :error
  driver_options:

test:
  clients:
    default:
      database: speedway_mb25_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: mongodb+srv://<%= ENV['ATLAS_USER'] %>:<%= ENV['ATLAS_KEY'] %>@cluster90016.m6qysai.mongodb.net/speedway_mb25_production
